language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  app: ratemyride2
  api_key:
    secure: I2z6R/SvDmkLnNL7iAouNWpcmxKfBf8GBRFiMDAYS8BvrYCiaoiGPRFZmVZoEkFdqczGdRZXQ/moek+ASMljJS+dWabcyY5r3EK27BToYxa5mUv5Z34NS7mF4w7iS4OqESyPk9ve8LK/gJee4qUQQmo6mBnJxyi2UeOfo03GNPWUme7PEocNLNBo4tS0jY95P61IevoneLV1XR8CUBuNyH8a4LmfO3swpRzYlYLl8qQIK7QfWcUGWGsLKuWO1KF4Eyx4ubbAJp5VJttvkwk6TdHsT2I0u2a/F8ETm7zFEXSy+nKWlsymw54ueRhyYy4V12RGuPRoNUZPm7K1G3+pOasK1qm+JxFhqhUTDyu8u+hKyfyvgcVAsvTjyAtk6LdET+TM6rb8CYHuJaNLdk1worN5S5Jm3+J3T0M1ZfdwH7ZhKGFKM/mrUpOx5walMODuHTZ62qi6EVCl4bIjyfbiYRdVMJKChIwYkWXpBNlrp3oAa/9yoQrzuevAyRgByf6bo1FxxCT0nLXXpDoFUSaa8vfRTC2me5+NJFQYFefjoRA3q+qb8ACQKUcsvaoIsb2hDdUhffn8NoZ1/7A0iGadUB+GG81HfJiIZYEibpoaVVlzdJf7Hyc8VJ1/uel3sWoXrOfUpZKta79D/uwgYnSKcACaOYtUs/6OkIoBzpxuOO0=
