language: node_js
node_js: node
deploy:
  provider: heroku
  app: rate-my-ride
  api_key:
    secure: EI1mkxWuDEadInFtjYCuSZc74IC1eKwReX3erMNHMXlM4RBDoYa/niaBMjT6GCIhd1h+rdXhEglhEZRXRSk+kc+Nf8v+ybn5c5mm2LwEfnLSo+HykzFOi4ycEmd5Z/bTO2l/V9nbHZJbEHnkI+sfFTBhGpTrJUXhjbvzvD40rueMor/8Y1hInMe215QnxglnEhVkbQZMi0rV/LZyHsG3wJzSOzYfTb4dWRYPRp8I+8BCNt5z6HB1aUxEjl7XJw7/hfUXQre+bc9u4hH10Pac/Mkz1SILVeELKof3wforwvFrLMZ7FGtg3w7OZUHTlwb+TUSoZ0Wd1UG5dDmLWb9G1WT/1YWtAAJCD5bLKaDsrhopCIk5wdQBq2dDsk7A+057cjWjXgyIC6z6/ALdS4/N54X1qglQsMUdSXpTVRgsGRYJh34pv4Xspp7jl/1nvfI4JBavxfBYkQxvPzCBfnNTrdlFBtumUYfO12dFrfBER5pN30B8IDpBu27atIHMsdtS5cyTEXZxhn8jlBKKF5ABaDqKTLtnHn23iKqEcSJ8V6yAxD1OBJS2e37FBW+7xz4IIAOAi1frBSgZ9DYBRITRC5MEg8nzJ8wa05MkITV5LdNgtfsrQgIQmd2xe7FxzhPKas+JpaYo2pRGJydm49SwIxYgxRiIVEGdNEPj11Vypbc=
